onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /toptest/pushbutton
add wave -noupdate /toptest/PhaseA1
add wave -noupdate /toptest/DebugP2
add wave -noupdate /toptest/DebugP3
add wave -noupdate /toptest/PhaseC1
add wave -noupdate /toptest/PhaseC2
add wave -noupdate /toptest/PhaseC3
add wave -noupdate /toptest/PhaseC4
add wave -noupdate /toptest/PhaseA2
add wave -noupdate /toptest/PhaseA4
add wave -noupdate /toptest/Rst
add wave -noupdate /toptest/Rst1
add wave -noupdate /toptest/Rst2
add wave -noupdate /toptest/Sin1
add wave -noupdate /toptest/Sin2
add wave -noupdate /toptest/Sin3
add wave -noupdate /toptest/Sin4
add wave -noupdate /toptest/Sin5
add wave -noupdate /toptest/Sin6
add wave -noupdate /toptest/Sin7
add wave -noupdate /toptest/Sin8
add wave -noupdate /toptest/Sin9
add wave -noupdate /toptest/Sin10
add wave -noupdate /toptest/Sin11
add wave -noupdate /toptest/Sin12
add wave -noupdate /toptest/Sin14
add wave -noupdate /toptest/Sin15
add wave -noupdate /toptest/Sin16
add wave -noupdate /toptest/Clk1
add wave -noupdate /toptest/Clk2
add wave -noupdate /toptest/Clk3
add wave -noupdate /toptest/Clk4
add wave -noupdate /toptest/RS1
add wave -noupdate /toptest/RS2
add wave -noupdate /toptest/RS3
add wave -noupdate /toptest/RS4
add wave -noupdate /toptest/RS5
add wave -noupdate /toptest/RS6
add wave -noupdate /toptest/RS7
add wave -noupdate /toptest/RS8
add wave -noupdate /toptest/ADMode_1
add wave -noupdate /toptest/ADMode_2
add wave -noupdate /toptest/ADMode_3
add wave -noupdate /toptest/ADMode1_1
add wave -noupdate /toptest/ADMode1_2
add wave -noupdate /toptest/ADMode1_3
add wave -noupdate /toptest/ADRst1
add wave -noupdate /toptest/ADRst2
add wave -noupdate /toptest/ADRst3
add wave -noupdate /toptest/ADClk1
add wave -noupdate /toptest/ADClk2
add wave -noupdate /toptest/ADClk3
add wave -noupdate /toptest/ADSout1
add wave -noupdate /toptest/ADSout2
add wave -noupdate /toptest/ADSout3
add wave -noupdate /toptest/ADSout4
add wave -noupdate /toptest/ADSout5
add wave -noupdate /toptest/ADSout6
add wave -noupdate /toptest/ADSout7
add wave -noupdate /toptest/ADSout8
add wave -noupdate /toptest/ADSout15
add wave -noupdate /toptest/Sout1
add wave -noupdate /toptest/Sout2
add wave -noupdate /toptest/AD0
add wave -noupdate /toptest/AD1
add wave -noupdate /toptest/ClkOut
add wave -noupdate /toptest/DataOut
add wave -noupdate /toptest/ResCS1
add wave -noupdate /toptest/ResCS2
add wave -noupdate /toptest/ResCS3
add wave -noupdate /toptest/ResCS4
add wave -noupdate /toptest/ResCS5
add wave -noupdate /toptest/ResCS6
add wave -noupdate /toptest/ResCS7
add wave -noupdate /toptest/ResCS8
add wave -noupdate /toptest/ResClk
add wave -noupdate /toptest/ResSDI1
add wave -noupdate /toptest/ResSDI2
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {330464318 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {324827384 ps} {337505818 ps}
