/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Wed Aug 23 18:07:55 2023 */

/* parameterized module instance */
pll1 __ (.CLKI( ), .CLKOP( ));
