/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Sat Dec 17 20:07:14 2022 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
